/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ccntciicqpyvbmqppmne"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjbnRjaWljcXB5dmJtcXBwbW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NjIyNTAsImV4cCI6MjA3NzQzODI1MH0.KsHYwwsD56OpHPJI5ptXui-kUmX7Jga9OqaBv-BLi0A"